apiVersion: v1
kind: Service

metadata:
  name: grune-nodeport
  namespace: devops-test

spec:
  type: NodePort
  selector:
    app: grune-app
  ports:
    - name: http
      port: 8000 #service port inside the cluster
      targetPort: 8000 # port of the container
      nodePort: 30000 # port of the node

